# Generated by Django 4.2.23 on 2025-07-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_data',
            name='admit_date',
        ),
        migrations.RemoveField(
            model_name='student_data',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student_data',
            name='standard',
        ),
    ]
