# Generated by Django 4.2.21 on 2025-07-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_student_data_admit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='faculty',
        ),
    ]
